# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: SynapplayOfficial.Synapplay
PackageVersion: "1.0"
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/synapplay-official/synapplay/releases/download/1.0/Synapplay-windows-1.0-x64-setup.exe
    InstallerSha256: 0E96AEE56E8C2564AB41166F6F479254BEC7F152C80F7735ABE694C5841D2F06
ManifestType: installer
ManifestVersion: 1.6.0
