# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.6.0.schema.json
PackageIdentifier: SynapplayOfficial.Synapplay
PackageVersion: "1.0"
PackageLocale: en-US
Publisher: Michael Langlais
PublisherUrl: https://universdemike.com
PackageName: Synapplay
PackageUrl: https://github.com/synapplay-official/synapplay
License: Proprietary
ShortDescription: Media server and client for series, movies and music, controlled by keyboard or gamepad in a game-console menu style.
Moniker: synapplay
Tags:
  - media-server
  - media-player
  - gamepad
  - series
  - movies
  - music
ManifestType: defaultLocale
ManifestVersion: 1.6.0
