# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.6.0.schema.json
PackageIdentifier: SynapplayOfficial.Synapplay
PackageVersion: "1.0"
InstallerType: inno
Scope: user
InstallModes:
  - interactive
  - silent
  - silentWithProgress
Installers:
  - Architecture: x64
    InstallerUrl: https://github.com/synapplay-official/synapplay/releases/download/1.0/Synapplay-windows-1.0-x64-setup.exe
    InstallerSha256: 209B350D1ED3465A733A3D1A9B411605FC54FE9C6B7FFADFFF2B26E57DE4FFFE
ManifestType: installer
ManifestVersion: 1.6.0
